---
title: "Subnational Visualizations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Subnational Visualizations}
  %\usepackage[UTF-8]{RtD3}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(RtD3)
```

## Overview

RtD3 supports visualizations for subnational estimates using the same interface. Data must have the same structure and columns as global data. 

## India

Plotting subnational estimates requires that column names are identical to the columns required from global estimates. 

```{r }
geoData <- rnaturalearth::ne_states('India', returnclass = 'sf') %>% 
  rename(sovereignt = name_en)

# Read in each summary folder
rtData <- list("Cases" = 
RtD3::readInEpiNow2(path = "https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/master/subnational/india/cases/summary",
                    region_var = "region"))
```


This data is then passed to `RtD3::summaryWidget`.

``` {r echo=F}

RtD3::summaryWidget(
  geoData = geoData,
  rtData = rtData,
  activeArea = 'Sikkim'
)

```
